import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from harness.tools.github_tools import build_pr_body, github_create_pr


@dataclass(frozen=True)
class GitCommandResult:
    command: list[str]
    stdout: str
    stderr: str
    returncode: int


def prepare_pull_request(
    *,
    repo_path: str,
    task_id: str,
    title: str,
    summary: str,
    evaluation: dict[str, Any] | None = None,
    github_repo: str | None = None,
    base_branch: str = "main",
    dry_run: bool = True,
) -> dict[str, Any]:
    repo = Path(repo_path).resolve()
    branch = f"agent/{_slug(title)}-{task_id[:8]}"
    commit_message = f"{title.strip() or 'Harness generated patch'}\n\nGenerated by autonomous harness task {task_id}."
    status = _git(repo, ["status", "--short"])
    has_changes = bool(status.stdout.strip())
    pr_body = build_pr_body(summary=summary, evaluation=evaluation or {}, repo_path=str(repo))

    result: dict[str, Any] = {
        "dry_run": dry_run,
        "repo_path": str(repo),
        "branch": branch,
        "base_branch": base_branch,
        "commit_message": commit_message,
        "has_changes": has_changes,
        "status": status.stdout,
        "pr_body": pr_body,
        "commands": [],
    }

    if dry_run:
        result["commands"] = [
            ["git", "checkout", "-B", branch],
            ["git", "add", "-A"],
            ["git", "-c", "user.name=Autonomous Harness", "-c", "user.email=harness@example.local", "commit", "-m", commit_message],
            ["git", "push", "-u", "origin", branch],
        ]
        if github_repo:
            result["pull_request"] = github_create_pr(
                repo=github_repo,
                title=title,
                body=pr_body,
                head=branch,
                base=base_branch,
                dry_run=True,
            )
        return result

    if not has_changes:
        result["skipped"] = "no_changes"
        return result

    commands = [
        _git(repo, ["checkout", "-B", branch]),
        _git(repo, ["add", "-A"]),
        _git(
            repo,
            [
                "-c",
                "user.name=Autonomous Harness",
                "-c",
                "user.email=harness@example.local",
                "commit",
                "-m",
                commit_message,
            ],
        ),
    ]
    result["commands"] = [_serialize(command) for command in commands]

    failed = next((command for command in commands if command.returncode != 0), None)
    if failed:
        result["error"] = failed.stderr or failed.stdout
        return result

    if github_repo:
        push = _git(repo, ["push", "-u", "origin", branch])
        result["commands"].append(_serialize(push))
        if push.returncode != 0:
            result["error"] = push.stderr or push.stdout
            return result
        result["pull_request"] = github_create_pr(
            repo=github_repo,
            title=title,
            body=pr_body,
            head=branch,
            base=base_branch,
            dry_run=False,
        )
    return result


def _git(repo: Path, args: list[str]) -> GitCommandResult:
    proc = subprocess.run(["git", *args], cwd=repo, capture_output=True, text=True, timeout=60)
    return GitCommandResult(command=["git", *args], stdout=proc.stdout, stderr=proc.stderr, returncode=proc.returncode)


def _serialize(result: GitCommandResult) -> dict[str, Any]:
    return {
        "command": result.command,
        "stdout": result.stdout,
        "stderr": result.stderr,
        "returncode": result.returncode,
    }


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.lower()).strip("-")
    return slug[:48] or "task"
